# Generated by Django 6.0.8 on 2026-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_collection_colophon_alter_theme_colophon'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='disaron_id',
            field=models.CharField(blank=True, help_text='Unique publication identifier. Shown at the bottom of the page.', max_length=255, null=True, unique=True, verbose_name='Disaron identifier (former Agreste)'),
        ),
    ]
